version: '3'

services:
  app:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src/app
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres
    container_name: database
    restart: always
    env_file:
      - .env.example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: